version: '3.8'

services:
  # 1. Server API (Inference)
  inference-app:
    build: .                 # <-- UBAH INI (Hapus /Monitoring)
    container_name: inference_model
    ports:
      - "5000:5000"
    networks:
      - mlops-net

  # 2. Prometheus (Pencatat Data)
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_server
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # <-- UBAH INI (Hapus /Monitoring)
    ports:
      - "9090:9090"
    networks:
      - mlops-net

  # 3. Grafana (Dashboard Keren)
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_dashboard
    ports:
      - "3000:3000"
    networks:
      - mlops-net
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

networks:
  mlops-net:
    driver: bridge