name: CI/CD Pipeline MLOps Renn

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build-and-train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        # Kita install library dari file requirements yang ada di folder baru
        # Pastikan path ini sesuai dengan struktur folder kamu di GitHub
        if [ -f Workflow-CI/MLProject/requirements.txt ]; then
          pip install -r Workflow-CI/MLProject/requirements.txt
        elif [ -f MLProject/requirements.txt ]; then
          pip install -r MLProject/requirements.txt
        else
          echo "Requirements.txt tidak ditemukan!"
          exit 1
        fi

    - name: Run Model Training & Track to DagsHub
      env:
        # Kita hanya butuh Token ini, karena URI sudah ada di dalam script python
        DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
      run: |
        # Robot menjalankan script modelling dari folder yang benar
        if [ -f Workflow-CI/MLProject/modelling.py ]; then
          python Workflow-CI/MLProject/modelling.py
        elif [ -f MLProject/modelling.py ]; then
          python MLProject/modelling.py
        else
          echo "Script modelling.py tidak ditemukan!"
          exit 1
        fi
